### ISSUE TITLE
New release version v0.28.0 doesn't contain the latest commit a60d2863d94aea91dde9bb4833b5d9eb86c7cf7c

### ISSUE THREAD

**Issue by cbairy** [asticode/astilectron#11]
Hi asticode,
The latest version of the release v0.28.0 doesn't contain the latest changes made on astilectron/main.js file.
Thanks,
Chandrakanth.

**Comment by asticode** [comment]
@cbairy you're right, will create a new tag

**Comment by asticode** [comment]
@cbairy I'vre created a `v0.29.0` tag and I've bumped version in `go-astilectron` as well.

I'll close this issue but let me know if you're still having an issue.
