### ISSUE TITLE
Electron version 4.0.1 does not have method named "app.makeSingleInstance"

### ISSUE THREAD

**Issue by sam-kamerer** [asticode/astilectron#13]
https://github.com/asticode/astilectron/blob/a60d2863d94aea91dde9bb4833b5d9eb86c7cf7c/main.js#L18

**Comment by asticode** [comment]
Should be all good now.

Can you confirm?

**Comment by sam-kamerer** [comment]
Yes, it's works.
Thanks for fast fix.
