### ISSUE TITLE
clear electron cache

### ISSUE THREAD

**Issue by HeavyHorst** [asticode/astilectron#2]
is there a way to clear the electron cache (besides rm -rf ~/.config/Electron/cache) ?

**Comment by asticode** [comment]
@HeavyHorst do you mean like clearing the HTTP cache?

https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearcachecallback

**Comment by HeavyHorst** [comment]
yes, like clearing the http cache.

I would like to clear the cache from within go-astilectron.
I think this functionality needs to be exported from here ?

**Comment by asticode** [comment]
Great idea, I've created this issue in [go-astilectron](https://github.com/asticode/go-astilectron/issues/56)'s repo instead
