### ISSUE TITLE
File Dialogs and Notifications

### ISSUE THREAD

**Issue by winwisely99** [asticode/astilectron#24]
This golang lib does File Dialogs and Notifications cross platform:

https://github.com/ncruces/zenity

Does this help ? Or do you call into the Electron code and get it to do File Dialogues and Notifications. Sorry that i do not understand fully so got to ask.

**Comment by adambrakhane** [comment]
You could use either one. It looks like astielectron doesn't support Electron notifications yet so if you were looking to pop up a window, the package you linked would work instead.

**Comment by asticode** [comment]
@winwisely99 no worries. `astilectron` calls `electron` directly so this is not useful for `astilectron`. But as @adambrakhane mentions, as notifications require signing your app, and signing is not yet part of the bundler process, [notifications](https://github.com/asticode/go-astilectron#notifications) are not fully available in `astilectron`. Therefore this lib could be a good backup plan until notifications are fully up and running in `astilectron`.

Regarding file dialogs, you can already [use them](https://github.com/asticode/go-astilectron#dialogs) directly in your JS.
