### ISSUE TITLE
[discuss](added some webContents event)

### ISSUE THREAD

**Issue by ZEROKISEKI** [asticode/astilectron#3]
Wow, in general, oauth always requires a `redirect_uri`(such as the github oauth),  but electron usually use a filePath like that:

```

const w = new BrowserWindow({});
w.loadURL("file://path to project/index.html");         // use file path to .html

```

if the `redirect_uri` to set the file path, it will fail. If we want to use oauth in electron, there will be a way:  open a new sub window to load the oauth url which the redirect_uri set to `http://localhost`,  and electron listen `will-navigate`(when you first oauth) and `did-get-redirect-request`(when you have authorized)  to send the newUrl. Like what the [electron-oauth2](https://github.com/mawie81/electron-oauth2/)  do.

I found that boths `go-astilectron` and `astilectron` do not define this event, I forked the projects and modify it:

```
astilectron/src/consts.js:

windowEventDidGetRedirectRequest: "window.event.did.get.redirect.request",
windowEventWillNavigate: "window.event.will.navigate",   // will trigger when first use oauth
```

```
astilectron/main.js:

function windowCreate(json) {
      ...
     elements[json.targetID].webContents.on('did-get-redirect-request', (event, oldUrl, newUrl) => {
        client.write(json.targetID, consts.eventNames.windowEventDidGetRedirectRequest, {
            url: newUrl
        })
    })
    elements[json.targetID].webContents.on('will-navigate", (event, url) => {
        client.write(json.targetId, consts.eventNames.windowEventWillNavigate, {
            url
        })
    })
}
```

```
go-astilectron/window.go:

EventNameWindowEventDidGetRedirectRequest = "window.event.did.get.redirect.request"
EventNameWindowEventWillNavigate                    = "window.event.will.navigate"
```

I modified it in my forking `astilectron` project and release a `v.0.15.0` version(beacuse go-astilectron use `VersionAstilectron` and this attr is defined to `0.15.0`), and I try this in my project and test it:

```

var ow, _ = a.NewWindow("http://github.com/login/oauth/authorize?response_type=code&client_id=31dbd4e343e060a20bdf&client_secret=c0a20c8b3bd912998779ad639077442e6b8b3ba9&redirect_uri=http://localhost", &astilectron.WindowOptions{
	Center: astilectron.PtrBool(false),
	Height: astilectron.PtrInt(600),
	Width:  astilectron.PtrInt(600),
})

ow.On(astilectron.EventNameWindowEventDidGetRedirectRequest, func(e astilectron.Event) (deleteListener bool) {
	w.SendMessage(e.URL, func(m *astilectron.EventMessage) {
		// Unmarshal
		var s string
		m.Unmarshal(&s)

		// Process message
		astilog.Debugf("received %s", s)
	})
	return
})

ow.On(astilectron.EventNameWindowEventWillNavigate, func(e astilectron.Event) (deleteListener bool) {
	w.SendMessage(e.URL, func(m *astilectron.EventMessage) {
		// Unmarshal
		var s string
		m.Unmarshal(&s)

		// Process message
		astilog.Debugf("received %s", s)
	})
	return
})

```

this gif is what I tested result:

![1](https://user-images.githubusercontent.com/9923459/37860636-7cc7cc26-2f64-11e8-9fe4-73a55fb7fc27.gif)

this can use to other aspects that load url, I'm no sure what your opinion about this, so I open an issue to discuss it, if you think it is feasible, I will make some PR.

**Comment by asticode** [comment]
@ZEROKISEKI this sounds like a good idea to me. But that would be easier to discuss it in a PR process. Could you make PRs referencing this issue, and we'll continue the discussion over there.

Cheers
