### ISSUE TITLE
State changes are not working properly with Astilectron + Angular

### ISSUE THREAD

**Issue by komyg** [asticode/astilectron#30]
Hi,

I have an app that uses Angular 10 and NgRx, and I am having some difficulties with its state changes. 

The problem is that the UI is not updating correctly given the state of the app. For example, if I click on a button to open a modal popup, the modal doesn't show until I click on something else on the UI and force it to update.

I've tested my app on the latest version of Chrome and on the latest version of Electron (9.1.2) and it worked fine. I also upgrade the Electron from Astilectron to version 9.1.2 but the error remained.

Here is an example:

![astilectron](https://user-images.githubusercontent.com/25157901/89544595-b357b980-d7d8-11ea-9370-b00951e0f810.gif)

Notice that the modal only appears after I click on the arrows that change the screen.

This is how it looks like in Chrome when it is working:

![astilectron-2](https://user-images.githubusercontent.com/25157901/89545211-74763380-d7d9-11ea-9efa-7e31a015f6e7.gif)

Has anyone experienced this? Can anyone help me?

Thanks,
Felipe

**Comment by asticode** [comment]
Answering in https://github.com/asticode/go-astilectron/issues/266
