### ISSUE TITLE
`package.json`'s `version` field isn't up to date

### ISSUE THREAD

**Issue by frazeradam** [asticode/astilectron#50]
Inspecting the history it appears that it got set at "0.33.0" for v0.33.0, but has not been updated since.

I'd like to suggest that either this be kept up to date, or it be removed and an alternative method of finding the version for an install be provided.  Thanks!

**Comment by asticode** [comment]
Out of curiosity, what problem are you experiencing when this `version` value is out of sync with the real `tag` ?

**Comment by frazeradam** [comment]
We are manually managing the dependencies (astilectron and electron) and are looking to use a similar code pattern to what we use for other files where we check the version, and update it if it's less than the minimum version we need.  Since we only plan to keep one version around, we're not including the version number in the folder path.

**Comment by asticode** [comment]
Version has been updated
